name: Decrypt IPA and Apply Pyzule

on:
  workflow_dispatch:
    inputs:
      ipa_link:
        description: 'Enter the decrypted IPA link'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y unzip curl python3 python3-venv libxml2-utils
        
    - name: Install Pyzule
      run: bash -c "$(curl https://raw.githubusercontent.com/asdfzxcvbn/pyzule/main/install-pyzule.sh)"

    - name: Download DaisukesPyoncord.pyzule
      run: curl -L -o DaisukesPyoncord.pyzule https://github.com/daisuke1227/BunnyUpdates/raw/main/DaisukesPyoncord.pyzule

    - name: Download DaisukesPyoncordWithNotifier.pyzule
      run: curl -L -o DaisukesPyoncordWithNotifier.pyzule https://github.com/daisuke1227/BunnyUpdates/raw/main/DaisukesPyoncordWithNotifier.pyzule

    - name: Extract IPA version
      id: get_version
      run: |
         mkdir ipa_contents
        curl -L -o decrypted.ipa "${{ github.event.inputs.ipa_link }}"
        unzip decrypted.ipa -d ipa_contents
        python3 -c "
import plistlib
from glob import glob

info_plist_path = glob('ipa_contents/Payload/*.app/Info.plist')[0]
with open(info_plist_path, 'rb') as f:
    plist_data = plistlib.load(f)
    ipa_version = plist_data.get('CFBundleShortVersionString')
    print(f'::set-output name=version::{ipa_version}')
"

    - name: Apply DaisukesPyoncord.pyzule
      run: pyzule -i decrypted.ipa -z DaisukesPyoncord.pyzule -o Bunny-checkversion-${{ steps.get_version.outputs.version }}-Daisuke.ipa

    - name: Apply DaisukesPyoncordWithNotifier.pyzule
      run: pyzule -i decrypted.ipa -z DaisukesPyoncordWithNotifier.pyzule -o BunnyWithUpdateNotifier-checkversion.0-${{ steps.get_version.outputs.version }}-Daisuke.ipa

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        release_name: Release v${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload Bunny-checkversion IPA to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Bunny-checkversion-${{ steps.get_version.outputs.version }}-Daisuke.ipa
        asset_name: Bunny-checkversion-${{ steps.get_version.outputs.version }}-Daisuke.ipa
        asset_content_type: application/octet-stream

    - name: Upload BunnyWithUpdateNotifier-checkversion IPA to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./BunnyWithUpdateNotifier-checkversion.0-${{ steps.get_version.outputs.version }}-Daisuke.ipa
        asset_name: BunnyWithUpdateNotifier-checkversion.0-${{ steps.get_version.outputs.version }}-Daisuke.ipa
        asset_content_type: application/octet-stream
