name: Decrypt IPA and Apply Pyzule

on:
  workflow_dispatch:
    inputs:
      ipa_link:
        description: 'Enter the decrypted IPA link'
        required: true
        type: string
      ipa_version:
        description: 'Enter the version of the IPA'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y unzip curl libxml2-utils

    - name: Install Pyzule
      run: bash -c "$(curl https://raw.githubusercontent.com/asdfzxcvbn/pyzule/main/install-pyzule.sh)"

    - name: Download DaisukesPyoncord.pyzule
      run: curl -L -o DaisukesPyoncord.pyzule https://github.com/daisuke1227/BunnyUpdates/raw/main/DaisukesPyoncord.pyzule

    - name: Download DaisukesPyoncordWithNotifier.pyzule
      run: curl -L -o DaisukesPyoncordWithNotifier.pyzule https://github.com/daisuke1227/BunnyUpdates/raw/main/DaisukesPyoncordWithNotifier.pyzule

    - name: Download IPA
      run: |
        mkdir ipa_contents
        curl -L -o decrypted.ipa "${{ github.event.inputs.ipa_link }}"

    - name: Apply DaisukesPyoncord.pyzule
      run: pyzule -i decrypted.ipa -z DaisukesPyoncord.pyzule -o Bunny-${{ github.event.inputs.ipa_version }}-Daisuke.ipa

    - name: Apply DaisukesPyoncordWithNotifier.pyzule
      run: pyzule -i decrypted.ipa -z DaisukesPyoncordWithNotifier.pyzule -o BunnyWithUpdateNotifier-${{ github.event.inputs.ipa_version }}-Daisuke.ipa

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.ipa_version }}
        release_name: Release v${{ github.event.inputs.ipa_version }}
        draft: false
        prerelease: false

    - name: Upload Bunny IPA to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Bunny-${{ github.event.inputs.ipa_version }}-Daisuke.ipa
        asset_name: Bunny-${{ github.event.inputs.ipa_version }}-Daisuke.ipa
        asset_content_type: application/octet-stream

    - name: Upload BunnyWithUpdateNotifier IPA to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./BunnyWithUpdateNotifier-${{ github.event.inputs.ipa_version }}-Daisuke.ipa
        asset_name: BunnyWithUpdateNotifier-${{ github.event.inputs.ipa_version }}-Daisuke.ipa
        asset_content_type: application/octet-stream
